### ISSUE TITLE
Which bot token?

### ISSUE THREAD

**Issue by habeas81** [XanIves/DnD-Avrae-GUI#2]
Hello, 
in your setup instructions you stated we needed to create a .env file for the discord bot token.  Which discord bot token are you referring to?  Do we need the token from our implementation of AVRAE or do we need to create our own new bot token (meaning this install is actually creating a new/standalone discord bot for us?)

Thanks!

**Comment by XanIves** [comment]
Hello, 

Good question, the answer is that this tool is designed to work rather stand-offishly from the official Avrae bot, so you will need to make a separate, second bot account with its own unique token, rather than reuse the one you use for your Avrae bot.

This is a good question, and it’s one I’ll clarify in the documentation when I get to my computer in a few hours and have access to desktop formatting. Let me know if this clarifies the issue for you!
